# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-18.3':
    docker:
      - image: circleci/node:18.3
    working_directory: ~/libauth
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn run cov:send
      - run: yarn run cov:check
  'node-16':
    docker:
      - image: circleci/node:16
    working_directory: ~/libauth
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn run cov:send
      - run: yarn run cov:check
  'node-14':
    docker:
      - image: circleci/node:14
    working_directory: ~/libauth
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: yarn run cov:send
      - run: yarn run cov:check
  'benchmarks':
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/libauth
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn run bench

workflows:
  version: 2
  build:
    jobs:
      - 'node-14'
      - 'node-16'
      - 'node-18'
      - 'benchmarks'
